### PR TITLE
Update package for React-Admin 2.0

### PR DESCRIPTION
**Pull request by marcw**
I updated the dev dependencies to React 16. Peer dependencies are still the same though. 

I also created a UPGRADE file to reflect the changes of React Admin 2.0

### CODE REVIEW

**Review by djhi — APPROVED** [review]
Thanks!

**Comment by fzaninotto** [comment]
Needs an update for the latest changes in react-admin...

**Comment by djhi** [comment]
Yes, see https://github.com/marmelab/react-admin/blob/master/UPGRADE.md#aor-dependent-input-was-removed

**Comment by sidferreira** [comment]
@fzaninotto @djhi @marcw any news on that?

**Comment by fzaninotto** [comment]
No news on that: this package is no longer needed in react-admin, since the feature it brings is supported in react-admin core via `FormDataConsumer`. So I guess this PR can be closed - `aor-dependent-input` will never work with react-admin.

**Pull request closed without merging**
