### PR TITLE
[RFR] Make it work with multiple children

### PR DESCRIPTION
**Pull request by djhi**
Supersedes #3

### CODE REVIEW

**Comment by wedneyyuri** [comment]
Returning multiple elements wrapped by a div will case unexpected behavior (Sports and TV shouldn't side by side):

image

**Comment by djhi** [comment]
You can still use it by giving it a single child. Styles for components can be overridden so it should be easy to customize and we can support both

**Comment by djhi** [comment]
Result with the following code:
```js
<DependentInput dependsOn="price">
    <NumberInput source="size.width" />
    <NumberInput source="size.height" />
</DependentInput>
```
screen

And with custom styles passed to children:
```js
<DependentInput dependsOn="price">
    <NumberInput source="size.width" style={{ display: 'inline-block' }} elStyle={{ width: '5em' }} />
    <NumberInput source="size.height" style={{ display: 'inline-block' }} elStyle={{ width: '5em' }} />
</DependentInput>
```
screen

Bonus: children have correct classes making it easier to target them in selenium tests

**Comment by wedneyyuri** [comment]
Looks good, much better now (y)

**Review by fzaninotto — APPROVED** [review]

**Pull request merged**
